language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - export PYTHONPATH=${PYTHONPATH}:${PWD}/src
  - python -m pytest tests/
branches:
  only:
   - master